CREATE TABLE `operation_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `biz_id` bigint NOT NULL COMMENT '业务ID',
  `biz_type` varchar(50) NOT NULL COMMENT '业务类型',
  `operation_type` varchar(50) DEFAULT NULL COMMENT '操作类型',
  `operation_detail` text COMMENT '操作详情JSON，记录变更前后的具体内容',
  `message` text NOT NULL COMMENT '操作概要，用于前端展示',
  `operator_id` bigint NOT NULL COMMENT '操作人ID',
  `operator` varchar(100) NOT NULL COMMENT '操作人姓名',
  `operation_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  `gmt_create` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `creator_id` bigint DEFAULT NULL COMMENT '创建人id',
  `creator_name` varchar(255) DEFAULT NULL COMMENT '创建人名称',
  `updater_id` bigint DEFAULT NULL COMMENT '更新人id',
  `updater_name` varchar(255) DEFAULT NULL COMMENT '更新人名称',
  `gmt_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `attributes` text COMMENT '扩展属性字段，内容为json',
  `is_del` tinyint NOT NULL DEFAULT '0' COMMENT '逻辑删除: 0-正常 1-删除',
  PRIMARY KEY (`id`),
  KEY `idx_biz_id_type` (`biz_id`,`biz_type`),
  KEY `idx_operator_id` (`operator_id`),
  KEY `idx_operation_time` (`operation_time`),
  KEY `idx_is_del` (`is_del`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作记录表';
